### ISSUE TITLE
Google caucus results are white

### ISSUE THREAD

**Issue by Amndeep7** [xentok/userstyles#1]
If you see here: https://www.google.com/search?q=iowa+caucus+results
You will see that the caucus results are not being properly styled.

![image](https://user-images.githubusercontent.com/2015821/73996376-742fd500-4929-11ea-8b52-d811dce2582a.png)

Would appreciate it if you could take a gander at it.  I gave it a look, but the class names are all random character strings and the nodes are all mostly all divs, so I'm not making any headway with modifying it myself.

**Comment by xentok** [comment]
Thank you for the report.
I will soon take a look at it and fix it.

**Comment by xentok** [comment]
I've fixed that.
Please confirm.
![capture 2020-03-07 21 29 06](https://user-images.githubusercontent.com/15173976/76143485-31455680-60bb-11ea-9a43-29c865b5b377.png)

**Comment by Amndeep7** [comment]
Looks great - thanks!
