### ISSUE TITLE
Google autocomplete text in a dark/unreadable font

### ISSUE THREAD

**Issue by Amndeep7** [xentok/userstyles#3]
## Description about the bug
The autocomplete options that Google provides are unreadable due to being in a very dark font.

## Screenshots and URLs
![image](https://user-images.githubusercontent.com/2015821/119070567-3dfb5500-b9b6-11eb-985c-485bd2b87f91.png)

## Environments
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Version: 88.01

**The userstyles version:**
 - Google Clean Dark Customized v2.3.13

**Additional context**
n/a

**Comment by xentok** [comment]
Thanks, I've fixed that.
